services:

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data
    expose:
      - "6379"


  app1:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: server_app1
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./backend/src/.env
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-mydb}
    volumes:
      - ../logs/backend:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped


  app2:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: server_app2
    ports:
      - "8001:8000"
    expose:
      - "8000"
    env_file:
      - ./backend/src/.env
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-mydb}
    volumes:
      - ../logs/backend:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped



        

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html   # vite build 결과물
      - ../logs/nginx:/var/log/nginx  # 로그
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'" #  주기적으로 설정 리로드

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/lib:/var/lib/letsencrypt
      

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  redis_data: