"""update schema

Revision ID: 9e453c2dce01
Revises: 76225ca2cc0f
Create Date: 2025-10-11 14:53:08.258125

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e453c2dce01'
down_revision: Union[str, Sequence[str], None] = '76225ca2cc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    
    # nullable true 로 초기 설정
    op.add_column('token', sa.Column('device_id', sa.Uuid(), nullable=True))

    # 기존 데이터들의 디폴트 값 채우기
    tokens = conn.execute(sa.text("SELECT id FROM token")).fetchall()
    for token_id, in tokens:
        conn.execute(
            sa.text("UPDATE token SET device_id = :uuid WHERE id = :id"),
            {"uuid": str(uuid.uuid4()), "id": token_id}
        )

    # nullable false 로 업데이트
    op.alter_column('token', 'device_id', nullable=False)
    op.alter_column('trainsession', 'activity_id',
            existing_type=sa.INTEGER(),
            nullable=True)
    op.drop_index(op.f('ix_trainsession_activity_id'), table_name='trainsession')
    op.drop_constraint(op.f('uq_provider_activity'), 'trainsession', type_='unique')
    # ### end Alembic commands ###
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_provider_activity'), 'trainsession', ['provider', 'activity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trainsession_activity_id'), 'trainsession', ['activity_id'], unique=False)
    op.alter_column('trainsession', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('token', 'device_id')
    # ### end Alembic commands ###
