name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Node 설치 (GitHub Actions 환경)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 프론트 의존성 설치 & 빌드
      - name: Build Frontend
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      # 서버의 이전 dist 디렉토리 "전체"를 삭제
      - name: Clean old build directory on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ~/personal-running-coach/frontend/dist

      # 프론트 빌드파일 업로드
      - name: Upload Frontend dist to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "frontend/dist/*"
          target: "~/personal-running-coach/"

      # 백엔드 배포 (docker-compose)
      - name: Deploy backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/personal-running-coach
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build