# .github/workflows/deploy.yml
name: Deploy to Server

# main 브랜치에 push될 때만 동작
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 서버 SSH 접속 후 배포 실행
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/personal-running-coach-backend           # 서버 내 프로젝트 디렉토리
            git pull origin main                # 최신 코드 가져오기
            docker compose -f docker-compose.prod.yml up -d --build
